/**
 * Copyright (C) 2026 to the present, Crestron Electronics, Inc.
 * All rights reserved.
 * No part of this software may be reproduced in any form, machine
 * or natural, without the express written consent of Crestron Electronics.
 * Use of this source code is subject to the terms of the Crestron Software License Agreement 
 * under which you licensed this source code.  
 *
 * This code was automatically generated by Crestron's code generation tool.
*/
/*jslint es6 */
/*global serviceModule, CrComLib */

const mainModule = (() => {
  'use strict';

  // BEGIN::CHANGEAREA - your javascript for page module code goes here   
  // ========== 全局状态 ==========
  let panelConfig = null;
  let currentPageIndex = 0;
  const configUrl = './app/project/components/pages/main/test.json';

  // ========== DOM 引用 ==========
  let mainContent = null
  let bottomTabs = null
  let themeToggle = null;
  let appTitle = null;
  let appSubTitle = null;
  const body = document.body;

  /**
   * Initialize Method
   */
  function onInit() {
    //serviceModule.addEmulatorScenarioNoControlSystem("./app/project/components/pages/main/main-emulator.json");
    // Uncomment the below line and comment the above to load the emulator all the time.
    serviceModule.addEmulatorScenario("./app/project/components/pages/main/main-emulator.json");
    initDOM();
    initTheme();
    loadConfig(configUrl);
  }

  // ========== DOM 初始化 ==========
  function initDOM() {
    mainContent = document.getElementById('mainContent');
    bottomTabs = document.getElementById('bottomTabs');
    themeToggle = document.getElementById('themeToggle');
    appTitle = document.getElementById('app-title');
    appSubTitle = document.getElementById('app-subTitle');
    themeToggle.addEventListener('click', toggleTheme);
  }

  // ========== 主题管理 ==========
  function initTheme() {
    const saved = localStorage.getItem('panel-theme');
    if (saved === 'dark') {
      body.classList.add('dark-theme');
    } else {
      body.classList.remove('dark-theme');
    }
  }

  function toggleTheme() {
    body.classList.toggle('dark-theme');
    const isDark = body.classList.contains('dark-theme');
    localStorage.setItem('panel-theme', isDark ? 'dark' : 'light');
  }


  // ========== 加载配置文件 ==========
  async function loadConfig(configUrl) {
    try {
      const response = await fetch(configUrl);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      panelConfig = await response.json();
      buildTitle(panelConfig);

      fullRender(panelConfig);
    } catch (err) {
      mainContent.innerHTML = `
        <div class="error-message">
          <p class="error-icon" >⚠️</p>
          <p>配置文件加载失败</p>
          <p>错误信息：${err}</p>
          <p>请检查 ${configUrl} 是否存在，并且格式正确</p>
        </div>`;
    }
  }

  // ========== 转义工具 ==========
  function escapeHtml(str) {
    return String(str).replace(/[&<>"]/g, m => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'
    })[m]);
  }

  // ========== 图标渲染辅助 ==========
  function renderIcon(iconClass) {
    if (!iconClass) return '';
    return `<i class="${iconClass}" ></i>`;
  }

  // CH5 Button 控件构建函数，外观与普通按钮相同，但点击时会发送特定事件
  function createCh5ButtonControl(control, wrapper) {
    const btn = document.createElement('ch5-button');

    // 创建ch5-button-label元素并设置内容
    const btnLabel = document.createElement('ch5-button-label');

    // 设置内部HTML内容
    btnLabel.innerHTML = `${renderIcon(control.icon)}  ${escapeHtml(control.label)} `;
    btnLabel.innerHTML = '<div class="ch5-button-custom-label">' + btnLabel.innerHTML + '</div>';
    btnLabel.innerHTML = '<template>' + btnLabel.innerHTML + '</template>';
    btn.appendChild(btnLabel);

    btn.stretch = 'both';

    btn.sendEventOnClick = control.join ? control.join  : '';
    btn.receiveStateSelected = control.join ? control.join + "_Fb" : '';
    btn.receiveStateEnable = control.enable || '';

    btn.addEventListener('click', (e) => {
      showNotification(`执行: ${control.join || 'no-action'}`);
    });
    wrapper.appendChild(btn);
  }

  // 文本控件构建函数
  function createLabelControl(control, wrapper) {
    const text = document.createElement('div');
    text.className = 'text-control';
    text.innerHTML = `${renderIcon(control.icon)} <span>${escapeHtml(control.label)} </span>`;
    wrapper.appendChild(text);
  }

  // ========== 通知提示 ==========
  function showNotification(message) {
    const notification = document.createElement('div');
    notification.className = 'notification';
    notification.innerHTML = `${renderIcon('fas fa-check')} ${message}`;
    document.body.appendChild(notification);

    setTimeout(() => {
      if (notification.parentNode) {
        notification.parentNode.removeChild(notification);
      }
    }, 2500);
  }


  // ========== 渲染当前页面 ==========
  function renderCurrentPage() {
    if (!panelConfig || !panelConfig.pages[currentPageIndex]) return;
    const pageData = panelConfig.pages[currentPageIndex];
    const pagePanel = document.querySelector(`.page-panel[data-page-id="${pageData.id}"]`);
    if (!pagePanel) return;

    pagePanel.innerHTML = '';
    pagePanel.style.gridTemplateColumns = '';
    pageData.sections.forEach(section => {
      const sectionDiv = document.createElement('div');
      sectionDiv.className = 'section';
      sectionDiv.style.flexGrow = section.widthRatio || 1;
      const titleDiv = document.createElement('div');
      titleDiv.className = 'section-title';
      titleDiv.innerHTML = `${renderIcon(section.icon)} ${escapeHtml(section.title)}`;
      sectionDiv.appendChild(titleDiv);

      const grid = document.createElement('div');
      grid.className = 'controls-grid';
      grid.style.gridTemplateColumns = `repeat(${section.columns || 1}, 1fr)`;

      section.controls.forEach(control => {
        const item = document.createElement('div');
        item.className = 'control-item';
        item.style.height = section.controlHeight || 'auto';
        switch (control.type) {
          case 'label': createLabelControl(control, item); break;
          case 'ch5-button': createCh5ButtonControl(control, item); break;
          default: item.textContent = `未知控件 ${control.type},检查配置文件`;
        }
        grid.appendChild(item);
      });

      sectionDiv.appendChild(grid);
      pagePanel.appendChild(sectionDiv);
    });
  }

  // ========== 构建所有页面结构 ==========
  function buildAllPages() {
    mainContent.innerHTML = '';
    panelConfig.pages.forEach((page, index) => {
      const pagePanel = document.createElement('div');
      pagePanel.className = 'page-panel';
      pagePanel.dataset.pageId = page.id;
      if (index !== currentPageIndex) {
        pagePanel.style.display = 'none';
      }
      mainContent.appendChild(pagePanel);
    });
    renderCurrentPage();
  }

  // ========== 底部标签导航 ==========
  function renderBottomTabs() {
    bottomTabs.innerHTML = '';
    panelConfig.pages.forEach((page, index) => {
      const btn = document.createElement('button');
      btn.className = 'tab-btn';
      btn.innerHTML = `${renderIcon(page.icon)} ${escapeHtml(page.name)}`;
      if (index === currentPageIndex) btn.classList.add('active');

      btn.addEventListener('click', () => {
        if (currentPageIndex === index) return;
        document.querySelectorAll('.page-panel').forEach((p, i) => {
          p.style.display = i === index ? 'flex' : 'none';
        });
        document.querySelectorAll('.tab-btn').forEach((b, i) => {
          b.classList.toggle('active', i === index);
        });
        currentPageIndex = index;
        renderCurrentPage();
      });

      bottomTabs.appendChild(btn);
    });
  }

  // ========== 完整渲染 ==========
  function fullRender(config) {
    if (!config) return;
    renderBottomTabs();
    buildAllPages();
  }

  // 标题栏
  function buildTitle(config) {
    appTitle.innerHTML = `${renderIcon(config.appTitle.icon || "fas fa-users")} ${escapeHtml(config.appTitle.text || '控制面板')}`;
    appSubTitle.innerHTML = `${escapeHtml(config.appTitle.version || '')}`;
  }

  window.reloadConfig = async function () {
    await loadConfig(configUrl);
  };

  /**
   * private method for page class initialization
   */
  let loadedSubId = CrComLib.subscribeState('o', 'ch5-import-htmlsnippet:main-import-page', (value) => {
    if (value['loaded']) {
      onInit();
      setTimeout(() => {
        CrComLib.unsubscribeState('o', 'ch5-import-htmlsnippet:main-import-page', loadedSubId);
        loadedSubId = '';
      });
    }
  });

  /**
   * All public method and properties are exported here
   */

  return {
  };

  // END::CHANGEAREA

})();


