/**
 * Copyright (C) 2026 to the present, Crestron Electronics, Inc.
 * All rights reserved.
 * No part of this software may be reproduced in any form, machine
 * or natural, without the express written consent of Crestron Electronics.
 * Use of this source code is subject to the terms of the Crestron Software License Agreement 
 * under which you licensed this source code.  
 *
 * This code was automatically generated by Crestron's code generation tool.
*/
/*jslint es6 */
/*global serviceModule, CrComLib */

const mainModule = (() => {
  'use strict';

  // BEGIN::CHANGEAREA - your javascript for page module code goes here   
  // ========== 全局状态 ==========
  let panelConfig = null;
  let currentPageIndex = 0;
  const configUrl = './app/project/components/pages/main/test.json';

  // ========== DOM 引用 ==========
  let mainContent = null
  let bottomTabs = null
  let themeToggle = null;
  let appTitle = null;
  let appSubTitle = null;
  const body = document.body;

  /**
   * Initialize Method
   */
  function onInit() {
    //serviceModule.addEmulatorScenarioNoControlSystem("./app/project/components/pages/main/main-emulator.json");
    // Uncomment the below line and comment the above to load the emulator all the time.
    serviceModule.addEmulatorScenario("./app/project/components/pages/main/main-emulator.json");
    initDOM();
    initTheme();
    loadConfig(configUrl);
  }

  // ========== DOM 初始化 ==========
  function initDOM() {
    mainContent = document.getElementById('mainContent');
    bottomTabs = document.getElementById('bottomTabs');
    themeToggle = document.getElementById('themeToggle');
    appTitle = document.getElementById('app-title');
    appSubTitle = document.getElementById('app-subTitle');
    themeToggle.addEventListener('click', toggleTheme);
  }

  // ========== 主题管理 ==========
  function initTheme() {
    const saved = localStorage.getItem('panel-theme');
    if (saved === 'dark') {
      body.classList.add('dark-theme');
    } else {
      body.classList.remove('dark-theme');
    }
  }

  function toggleTheme() {
    body.classList.toggle('dark-theme');
    const isDark = body.classList.contains('dark-theme');
    localStorage.setItem('panel-theme', isDark ? 'dark' : 'light');
  }


  // ========== 加载配置文件 ==========
  async function loadConfig(configUrl) {
    try {
      const response = await fetch(configUrl);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      panelConfig = await response.json();
      buildTitle(panelConfig);

      fullRender(panelConfig);
    } catch (err) {
      mainContent.innerHTML = `
        <div class="error-message">
          <p class="error-icon" >⚠️</p>
          <p>配置文件加载失败</p>
          <p>错误信息：${err}</p>
          <p>请检查 ${configUrl} 是否存在，并且格式正确</p>
        </div>`;
    }
  }

  // ========== 转义工具 ==========
  function escapeHtml(str) {
    return String(str).replace(/[&<>"]/g, m => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'
    })[m]);
  }

  // ========== 图标渲染辅助 ==========
  function renderIcon(iconClass) {
    if (!iconClass) return '';
    return `<i class="${iconClass}" ></i>`;
  }

  // CH5 Button 控件构建函数，外观与普通按钮相同，但点击时会发送特定事件
  function createCh5ButtonControl(control, wrapper) {
    const btn = document.createElement('ch5-button');

    // 创建ch5-button-label元素并设置内容
    const btnLabel = document.createElement('ch5-button-label');

    // 设置内部HTML内容
    btnLabel.innerHTML = `${renderIcon(control.icon)}  ${escapeHtml(control.label)} `;
    btnLabel.innerHTML = '<div class="ch5-button-custom-label">' + btnLabel.innerHTML + '</div>';
    btnLabel.innerHTML = '<template>' + btnLabel.innerHTML + '</template>';
    btn.appendChild(btnLabel);

    btn.setAttribute('stretch', 'both');
    //btn.setAttribute('sharp','rounded rectangle');

    btn.sendEventOnClick = control.join ? control.join : '';
    btn.receiveStateSelected = control.join ? control.join + "_Fb" : '';
    //btn.receiveStateEnable = control.join ? control.join + "_Enable" : '';

    btn.addEventListener('click', (e) => {
      showNotification(`执行: ${control.join || 'no-action'}`);
    });
    wrapper.appendChild(btn);
  }

  // 创建音量控件
  function createVolumeControl(control, wrapper) {
    const join = control.join || '';
    const label = document.createElement('div');
    label.setAttribute('classNaem', 'volume-label');
    label.innerHTML = `${escapeHtml(control.label)}`;

    const twoColumns = document.createElement('div');
    twoColumns.classList.add('dual-columns');
    const columnSlider = document.createElement('div');
    columnSlider.classList.add('volume-slider');

    const slider = document.createElement('ch5-slider');
    slider.setAttribute('orientation', 'vertical');
    slider.setAttribute('stretch','both');
    slider.setAttribute('min', '-40');
    slider.setAttribute('max', '10');
    slider.setAttribute('step', '1');
    slider.setAttribute('ticks', '{"0":"-40", "20":"-30", "40":"-20", "60":"-10", "80": "0", "100" : "10" }');
    slider.setAttribute('showTickValues', 'true');
    slider.setAttribute('tapSettable', 'true');
    slider.setAttribute('size', 'large');

    columnSlider.appendChild(slider);

    const columnButtons = document.createElement('div');
    columnButtons.classList.add('volume-buttons');

    const btnPlus = makeCh5Button('', 'fas fa-plus', join + '_plus', join + '_enable')
    const btnMinus = makeCh5Button('', 'fas fa-minus', join + '_minus', join + '_enable')
    const btnMute = makeCh5Button('', 'fas fa-volume-up', join + '_mute', join + '_enable')
    const value = document.createElement('div');
    value.classList.add('volume-value');
    value.innerHTML = '0';

    columnButtons.appendChild(value);
    columnButtons.appendChild(btnPlus);
    columnButtons.appendChild(btnMinus);
    columnButtons.appendChild(btnMute);

    twoColumns.appendChild(columnSlider);
    twoColumns.appendChild(columnButtons);

    slider.addEventListener('slider', (e) => {
      value.innerHTML = `${Math.floor(e.detail.value)}`;
    });
    slider.sendEventOnChange = join + '_Slider';
    slider.receiveStateValue = join + '_Slider_Fb';

    wrapper.appendChild(label);
    wrapper.appendChild(twoColumns);
  }

  //make ch5 button
  function makeCh5Button(label, icon, join, enable) {
    const btn = document.createElement('ch5-button');

    // 创建ch5-button-label元素并设置内容
    const btnLabel = document.createElement('ch5-button-label');

    // 设置内部HTML内容
    btnLabel.innerHTML = `${renderIcon(icon)}  ${escapeHtml(label)} `;
    btnLabel.innerHTML = '<div class="ch5-button-custom-label">' + btnLabel.innerHTML + '</div>';
    btnLabel.innerHTML = '<template>' + btnLabel.innerHTML + '</template>';
    btn.appendChild(btnLabel);

    btn.setAttribute('stretch' , 'both');
    //btn.stretch = 'both';

    btn.sendEventOnClick = join ? join : '';
    btn.receiveStateSelected = join ? join + "_Fb" : '';
    //btn.receiveStateEnable = enable || '';

    btn.addEventListener('click', (e) => {
      showNotification(`执行: ${join || 'no-action'}`);
    });
    return btn;
  }
  // 创建dpad控件
  function createDpadControl(control, wrapper) {
    const join = control.join || '';
    const dpadContain = document.createElement('div');
    dpadContain.classList.add('dpad-item');

    dpadContain.innerHTML = `<ch5-dpad stretch="height" shape="circle" contractName=${join}></ch5-dpad>`;


    const btnContain = document.createElement('div');
    btnContain.classList.add('dpad-buttons');

    const btnPlus = makeCh5Button('', 'fas fa-plus', join + '_plus', join + '_enable');
    const btnMinus = makeCh5Button('', 'fas fa-minus', join + '_minus', join + '_enable');

    btnContain.appendChild(btnPlus);
    btnContain.appendChild(btnMinus);

    wrapper.appendChild(dpadContain);
    wrapper.appendChild(btnContain);
  }

  // 视频切换控件

  function createVideoControl(control, wrapper) {
    const videoSwitch = document.createElement('ch5-video-switcher');
    //videoSwitch.numberofscreencolumns = 2;
    videoSwitch.setAttribute('contractName', "control.join || ''");
    //videoSwitch.setAttribute('sourcelistposition','left');
    if (control.sources) {
      control.sources.forEach(source => {
        const sourceElement = document.createElement('ch5-video-switcher-source');
        sourceElement.setAttribute('iconClass',`${source.icon}`);
        const sourceLabel = document.createElement('ch5-video-switcher-source-label');
        sourceLabel.innerHTML = `<template>${source.label}</template>`;
        sourceElement.appendChild(sourceLabel);
        videoSwitch.appendChild(sourceElement);
      });
    }
    videoSwitch.setAttribute('numberOfSoures', `${control.sources.length}`)
    if (control.screens) {
      control.screens.forEach(screen => {
        const screenElement = document.createElement('ch5-video-switcher-screen');
        const screenLabel = document.createElement('ch5-video-switcher-screen-label');
        screenLabel.innerHTML = `<template>${screen.label}</template>`;
        screenElement.appendChild(screenLabel);
        videoSwitch.appendChild(screenElement);
      });
    }
    videoSwitch.setAttribute('numberOfScreens', `4`);
    videoSwitch.setAttribute('numberOfScreenColumns', `2`);

    wrapper.appendChild(videoSwitch);
  }
  // 文本控件构建函数
  function createLabelControl(control, wrapper) {
    const text = document.createElement('div');
    text.classList.add('text-control');
    text.innerHTML = `${renderIcon(control.icon)} <span>${escapeHtml(control.label)} </span>`;
    wrapper.appendChild(text);
  }

  // ========== 通知提示 ==========
  function showNotification(message) {
    const notification = document.createElement('div');
    notification.classList.add('notification');
    notification.innerHTML = `${renderIcon('fas fa-check')} ${message}`;
    document.body.appendChild(notification);

    setTimeout(() => {
      if (notification.parentNode) {
        notification.parentNode.removeChild(notification);
      }
    }, 2500);
  }


  // ========== 渲染当前页面 ==========
  function renderCurrentPage() {
    if (!panelConfig || !panelConfig.pages[currentPageIndex]) return;
    const pageData = panelConfig.pages[currentPageIndex];
    const pagePanel = document.querySelector(`.page-panel[data-page-id="${pageData.id}"]`);
    if (!pagePanel) return;

    pagePanel.innerHTML = '';
    pagePanel.style.gridTemplateColumns = '';
    pageData.sections.forEach(section => {
      const sectionDiv = document.createElement('div');
      sectionDiv.className = 'section';
      sectionDiv.style.flexGrow = section.widthRatio || 1;
      const titleDiv = document.createElement('div');
      titleDiv.className = 'section-title';
      titleDiv.innerHTML = `${renderIcon(section.icon)} ${escapeHtml(section.title)}`;
      sectionDiv.appendChild(titleDiv);

      const grid = document.createElement('div');
      grid.className = 'controls-grid';
      grid.style.gridTemplateColumns = `repeat(${section.columns || 1}, 1fr)`;
      grid.style.gridTemplateRows = `repeat(${section.rows || 1}, 1fr)`;

      section.controls.forEach(control => {
        const item = document.createElement('div');
        item.className = 'control-item';
        //item.style.height = section.controlHeight || 'auto';
        switch (control.type) {
          case 'label': createLabelControl(control, item); break;
          case 'ch5-button': createCh5ButtonControl(control, item); break;
          case 'volume': createVolumeControl(control, item); break;
          case 'dpad': createDpadControl(control, item); break;
          case 'videoswitch': createVideoControl(control, item); break;

          default: item.textContent = `未知控件 ${control.type},检查配置文件`;
        }
        grid.appendChild(item);
      });

      sectionDiv.appendChild(grid);
      pagePanel.appendChild(sectionDiv);
    });
  }

  // ========== 构建所有页面结构 ==========
  function buildAllPages() {
    mainContent.innerHTML = '';
    panelConfig.pages.forEach((page, index) => {
      const pagePanel = document.createElement('div');
      pagePanel.className = 'page-panel';
      pagePanel.dataset.pageId = page.id;
      if (index !== currentPageIndex) {
        pagePanel.style.display = 'none';
      }
      mainContent.appendChild(pagePanel);
    });
    renderCurrentPage();
  }

  // ========== 底部标签导航 ==========
  function renderBottomTabs() {
    bottomTabs.innerHTML = '';
    panelConfig.pages.forEach((page, index) => {
      const btn = document.createElement('button');
      btn.className = 'tab-btn';
      btn.innerHTML = `${renderIcon(page.icon)} ${escapeHtml(page.name)}`;
      if (index === currentPageIndex) btn.classList.add('active');

      btn.addEventListener('click', () => {
        if (currentPageIndex === index) return;
        document.querySelectorAll('.page-panel').forEach((p, i) => {
          p.style.display = i === index ? 'flex' : 'none';
        });
        document.querySelectorAll('.tab-btn').forEach((b, i) => {
          b.classList.toggle('active', i === index);
        });
        currentPageIndex = index;
        renderCurrentPage();
      });

      bottomTabs.appendChild(btn);
    });
  }

  // ========== 完整渲染 ==========
  function fullRender(config) {
    if (!config) return;
    renderBottomTabs();
    buildAllPages();
  }

  // 标题栏
  function buildTitle(config) {
    appTitle.innerHTML = `${renderIcon(config.appTitle.icon || "fas fa-users")} ${escapeHtml(config.appTitle.text || '控制面板')}`;
    appSubTitle.innerHTML = `${escapeHtml(config.appTitle.version || '')}`;
  }

  window.reloadConfig = async function () {
    await loadConfig(configUrl);
  };

  /**
   * private method for page class initialization
   */
  let loadedSubId = CrComLib.subscribeState('o', 'ch5-import-htmlsnippet:main-import-page', (value) => {
    if (value['loaded']) {
      onInit();
      setTimeout(() => {
        CrComLib.unsubscribeState('o', 'ch5-import-htmlsnippet:main-import-page', loadedSubId);
        loadedSubId = '';
      });
    }
  });

  /**
   * All public method and properties are exported here
   */

  return {
  };

  // END::CHANGEAREA

})();


